### ISSUE TITLE
[EPIC]: Testground's Infrastructure as Code

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#147]
Background
---

ATM, testground infrastructure is written in bash scripts. This solves the initial task of using `eks` to execute test runs. 
Nevertheless, this is not enough to reliably use testground for: 

- [x] 1. Infra module upgrades
- [ ] 2. Metrics collection / aggregation
- [ ] 3. Logs collection / aggregation
- [ ] 4. Metrics / Logs storage
- [ ] 5. CI/CD for big network tests

Hence, we need to redesign the infrastructure to a layers, which will let us be more flexible on setups

- [ ] Layer 1 - Basic Infrastructure in EKS(AWS)
---

**Goal: Setup basics for the layers above**

- [x] 1. Control Plane + node groups + security groups + OIDC
- [x] 2. EBS, EFS, Autoscaling
- [x] S3 -> to check
- [x] 3. ArgoCD

TerraForm is how we are going to implement all 3 points

Every item in points above are treated as TerraForm modules

- [ ] https://github.com/celestiaorg/test-infra/issues/148
- [ ] https://github.com/celestiaorg/test-infra/issues/149

Layer 2 - Testground Applications(Mandatory)
---

**Goal: make it easy aka `helm chart`**

1. Master helm chart for testground, which contains: 
    1. helm charts for each of components that we have rn in `functions.sh`
    2. ArgoCD will take care of deployments

Required Components (caveats → we need to finalise which ones are DS/STS/RS): 

- [x] 1. Redis
  - [x] [this](https://github.com/celestiaorg/testground-infra/blob/master/k8s/eks/bash/functions.sh#L384)
- [x] 2. Multus
- [x] 3. Weave
- [x] 4. Flannel
  - [x] We user the Amazon CNI
- [ ] 5. Testground-Sidecar
- [ ] 6. Testground-Daemon
- [ ] 7. Sync-Service

- [ ] https://github.com/celestiaorg/test-infra/issues/150
- [ ] #151 

- [ ] Layer 3 - Add-ons(dashboards, metrics, observability logs)
---

**Goal: full visibility for the dev teams to analyse test runs**

Components -> We need to finalise which ones below are DS/STS/RS:

- [x] 1. Prometheus
- [x] 2. InfluxDB
- [x] 3. Promtail
- [x] 4. Grafana
- [ ] 5. Metrics Scraper (we need do develop it in-house) or this https://github.com/celestiaorg/test-infra/issues/179
- [ ] 6. Log Metrics Analysers

**Comment by Bidon15** [comment]
cc: @sysrex @jrmanes

**Comment by smuu** [comment]
Why do we need to develop the Metrics Scraper in-house? Can't we use Prometheus for scraping?

**Comment by Bidon15** [comment]
Cosmos support: https://github.com/celestiaorg/test-infra/issues/179

**Comment by Bidon15** [comment]
Grooming 10/03/2023: Moved to Q2 
Prob half a day to solve the PoC with 1 avail zone

**Comment by Bidon15** [comment]
Grooming 12/05/2023: 

Putting it to the board. It will be closed by https://github.com/celestiaorg/devops/issues/123

**Comment by Bidon15** [comment]
Closing as done https://github.com/celestiaorg/devops/issues/123
