### ISSUE TITLE
monitoring: Infrastructure Logs Alerts

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/test-infra#162]
## Description

Hello team,

The purpose of this ticket is to create and configure alerts and send notifications to Slack base on the logs messages.
We have to be able to detect that we're having issues on the logs (errors/warning/info/etc..) and send a message to Slack.

--- 

## Some interesting articles: 🧐

[Loki Rules](https://grafana.com/docs/loki/latest/rules/)
[loki_alerts](https://github.com/andreas-mausch/grafana-prometheus-loki-alertmanager-setup/blob/master/loki/loki_alerts.yml)
[setup_loki_alerts](https://blog.ruanbekker.com/blog/2020/11/06/how-to-setup-alerting-with-loki/)
[video](https://www.youtube.com/watch?v=LVTPBmBJkQA)

--- 

## Tasks:

- [ ] Create an specific channel for this (ping @Sevey to create it)
- [ ] Setup/Configure the Alertmanager
- [ ] Configure some alerts base on the logs
- [ ] Send notification to Slack

ℹ️ Note: all the configurations + alerts rules have to be as IaC, and we have to be able to replicate this services without any issue.

--- 

## Next steps:

- [ ]  .

--- 

## Other

You can keep the code in the [celestia-sre](https://github.com/celestiaorg/celestia-sre) repository.

--- 

Best 🚀 

Jose Ramon Mañes
