### ISSUE TITLE
[EPIC][Celestia-App]: Refactor existing features to reusable components

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#47]
Introduction 🖖
---
This epic contains all necessary features that need to be refactor out as reusable components for future ease of test development
As spinning up Celestia Application instances is a pre-requisite to every test-run, we need to make this setup process less redundant as well as let the test designer configure those components as they wish to via .toml file

What needs to be done 🧐
---

- [ ] https://github.com/celestiaorg/test-infra/issues/36
- [ ] https://github.com/celestiaorg/test-infra/issues/34
- [ ] https://github.com/celestiaorg/test-infra/issues/35
- [x] https://github.com/celestiaorg/test-infra/issues/33
- [ ] https://github.com/celestiaorg/test-infra/issues/40
- [x] https://github.com/celestiaorg/test-infra/issues/46
- [x] #143

**Comment by Bidon15** [comment]
Grooming 12/05/2023: 
moving to Q3 2023
