### ISSUE TITLE
[EPIC] #001 Big Blocks Implementation

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#77]
Tracking issue for implementation of Test Plan #55 Big Blocks 

- [x] https://github.com/celestiaorg/test-infra/issues/58
- [x] https://github.com/celestiaorg/test-infra/issues/60
- [x] https://github.com/celestiaorg/test-infra/issues/61
- [x] https://github.com/celestiaorg/test-infra/issues/62
- [x] https://github.com/celestiaorg/test-infra/issues/63
- [x] https://github.com/celestiaorg/test-infra/issues/65 (deprecated in favour of PFD test-plan)
- [x] https://github.com/celestiaorg/test-infra/issues/50
- [x] https://github.com/celestiaorg/test-infra/issues/121

**Comment by Bidon15** [comment]
This plan is regarded as finished and can be closed as we report the execution status of it in a big k8s cluster

**Comment by Bidon15** [comment]
Now thinking further, #65 will be better fit as a separate spin-off test-plan, where we have tested each DA node in separation and together 

Will be moved to a separate EPIC

**Comment by Bidon15** [comment]
We need to also think about seed node integration sooner than later 
https://github.com/celestiaorg/test-infra/issues/50
