### ISSUE TITLE
[EPIC] Benchmark Test-Plan for Bridge/Full nodes serving shares to LNs

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#83]
## Introduction

This epic contains issues on creating/implementing/execution/reporting for this test-plan

### Docs/Test-Plan creation

- [x] https://github.com/celestiaorg/test-infra/issues/79

### Test-Plan implementation 

- [x] https://github.com/celestiaorg/test-infra/pull/89

### Test-Plan Execution & Reporting

- [x] https://www.notion.so/celestiaorg/QA-Report-1-Many-BN-to-LNs-b2311b85757148a98fdbaaa58f121a5b?pvs=4
- [ ] Need to be retested once node gets bug fixes

**Comment by Bidon15** [comment]
@Bidon15 to introduce @derrandz the meaning and workflow for 
>  dev + Local runs on small size env

**Comment by Bidon15** [comment]
Closing as done
